use_frameworks!

platform :ios, '10.0'

target 'MVDownloader_Example' do

 pod 'MVDownloader', :path => '~/Desktop/MVDownloader/MVDownloader/MVDownloader'
 
  target 'MVDownloader_Tests' do
    inherit! :search_paths

    
  end
end
