# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift

os: osx
osx_image: xcode10.2

cache: cocoapods 
podfile: Example/Podfile
before_install: 
- gem install cocoapods
- pod repo update

script:
  - set -o pipefail && xcodebuild -version
  - set -o pipefail && xcodebuild -showsdks
  - set -o pipefail && xcodebuild -showdestinations -workspace Example/MVDownloader.xcworkspace -scheme MVDownloader-Example 
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -destination 'platform=iOS Simulator,OS=12.2,name=iPhone 7' -workspace Example/MVDownloader.xcworkspace -scheme MVDownloader-Example ONLY_ACTIVE_ARCH=NO
- pod lib lint MVDownloader.podspec 
 
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 77da8681-2751-43ad-90dc-92534067d0b3

notifications:
  email:
    recipients:
      - sharkesm@gmail.com
    on_success: always 
    on_failure: always 

