# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode7.3
#language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MVDownloader.xcworkspace -scheme MVDownloader-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint

language: swift

os: osx
osx_image: xcode10.2

cache: cocoapods 
podfile: Example/Podfile
before_install: 
- gem install cocoapods

env:
  matrix: 
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone 7' 

script:
  - set -o pipefail && xcodebuild -version
  - set -o pipefail && xcodebuild -showsdks 
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MVDownloader.xcworkspace -scheme MVDownloader-Example -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
  - pod lib lint MVDownloader.podspec 
 
notifications:
  email:
    recipients:
      - sharkesm@gmail.com
    on_success: always 
    on_failure: never 

